import type { MealLog, DishRating } from "./types";

export const initialMeals: MealLog[] = [
  {
    date: "2026-09-19",
    day: "Saturday",
    meal: "Dinner",
    location: "Waring Commons (West)",
    rating: 7.6,
    favorites: ["Marry Me Chicken", "Cheesecake"],
    dislikes: ["Guinness Beef Stew"],
    notes:
      "Buttered penne served instead of egg noodles. Beef stew was tough and lacked flavor. Marry Me chicken was the highlight.",
  },
  {
    date: "2026-09-20",
    day: "Sunday",
    meal: "Lunch (Brunch)",
    location: "Waring Commons (West)",
    rating: 7.3,
    favorites: ["Campfire Salmon"],
    dislikes: ["Weekend brunch pricing surcharge"],
    notes:
      "Salmon was the standout entree. Breakfast items were decent, hash browns crispy, and sausage spicy but slightly heavy. Disliked the higher weekend brunch rate.",
  },
  {
    date: "2026-09-20",
    day: "Sunday",
    meal: "Dinner",
    location: "Waring Commons (West)",
    rating: 8.2,
    favorites: ["Parma Cod", "Cheesecake Squares"],
    dislikes: ["Corn (unseasoned, plain)"],
    notes:
      "Rice pilaf substituted for barley pilaf (above average). Cod was well-cooked with a crispy seasoned crust. Corn lacked any seasoning. Cheesecake squares enjoyed again.",
  },
  {
    date: "2026-09-21",
    day: "Monday",
    meal: "Lunch",
    location: "Redifer Commons (On a Roll)",
    rating: 8.7,
    favorites: ["Italian Sub (Custom)"],
    dislikes: [],
    notes:
      "Half white toasted with banana peppers and chipotle ranch. Generous portion of meats and toppings; chipotle sauce was flavorful. More cost-effective than the South buffet.",
  },
  {
    date: "2026-09-21",
    day: "Monday",
    meal: "Dinner",
    location: "Waring Commons (West)",
    rating: 8.3,
    favorites: ["Shrimp Ravioli", "Restocked Brisket"],
    dislikes: ["First batch of Brisket (dry/tough)"],
    notes:
      "Shrimp ravioli was solid A-tier. Initial brisket was dry and tough, but a freshly replenished second plate was much more tender and saved the meal. Sliced potato side was average.",
  },
];

export const initialDishes: DishRating[] = [
  {
    date: "2026-09-19",
    meal: "Dinner",
    dish: "Marry Me Chicken",
    location: "Waring Commons",
    category: "Entree",
    rating: 9.0,
    sentiment: "Favorite",
    notes: "Top entree of Saturday dinner; tender chicken with rich, savory sauce.",
  },
  {
    date: "2026-09-19",
    meal: "Dinner",
    dish: "Cheesecake",
    location: "Waring Commons",
    category: "Dessert",
    rating: 8.5,
    sentiment: "Liked",
    notes: "Rich and creamy dessert; consistent quality.",
  },
  {
    date: "2026-09-19",
    meal: "Dinner",
    dish: "Guinness Beef Stew",
    location: "Waring Commons",
    category: "Entree",
    rating: 4.0,
    sentiment: "Disliked",
    notes: "Tough meat texture and weak, uninspired flavor.",
  },
  {
    date: "2026-09-19",
    meal: "Dinner",
    dish: "Buttered Penne",
    location: "Waring Commons",
    category: "Side / Pasta",
    rating: 6.5,
    sentiment: "Neutral",
    notes: "Substituted on the line in place of egg noodles; standard plain pasta.",
  },
  {
    date: "2026-09-20",
    meal: "Lunch (Brunch)",
    dish: "Campfire Salmon",
    location: "Waring Commons",
    category: "Entree",
    rating: 8.8,
    sentiment: "Favorite",
    notes: "Standout entree of Sunday brunch; flavorful, moist, and well-cooked.",
  },
  {
    date: "2026-09-20",
    meal: "Lunch (Brunch)",
    dish: "Shredded Hash Browns",
    location: "Waring Commons",
    category: "Side / Breakfast",
    rating: 8.0,
    sentiment: "Liked",
    notes: "Crispy exterior and properly fried texture.",
  },
  {
    date: "2026-09-20",
    meal: "Lunch (Brunch)",
    dish: "Andouille Sausage",
    location: "Waring Commons",
    category: "Side / Breakfast",
    rating: 7.2,
    sentiment: "Neutral",
    notes: "Good spicy kick, but noticeably greasy and heavy.",
  },
  {
    date: "2026-09-20",
    meal: "Lunch (Brunch)",
    dish: "Breakfast Items (General)",
    location: "Waring Commons",
    category: "Breakfast",
    rating: 7.0,
    sentiment: "Neutral",
    notes: "Decent standard buffet staples (scrambled eggs, waffles).",
  },
  {
    date: "2026-09-20",
    meal: "Dinner",
    dish: "Parma Cod",
    location: "Waring Commons",
    category: "Entree",
    rating: 8.5,
    sentiment: "Liked",
    notes: "Flaky and not overcooked; crispy seasoned topping added great texture.",
  },
  {
    date: "2026-09-20",
    meal: "Dinner",
    dish: "Rice Pilaf",
    location: "Waring Commons",
    category: "Side / Grain",
    rating: 7.5,
    sentiment: "Liked",
    notes: "Above-average rice; substituted on the buffet line for scheduled barley pilaf.",
  },
  {
    date: "2026-09-20",
    meal: "Dinner",
    dish: "Corn",
    location: "Waring Commons",
    category: "Side / Veg",
    rating: 4.5,
    sentiment: "Disliked",
    notes: "Extremely basic and plain; completely lacked seasoning or butter.",
  },
  {
    date: "2026-09-21",
    meal: "Lunch",
    dish: "Italian Sub (Custom)",
    location: "Redifer Commons (On a Roll)",
    category: "Entree / Deli",
    rating: 8.7,
    sentiment: "Favorite",
    notes:
      "Half white toasted with banana peppers and chipotle ranch; generous portion and good value compared to buffet.",
  },
  {
    date: "2026-09-21",
    meal: "Dinner",
    dish: "Shrimp Ravioli w/ Lobster Cream Sauce",
    location: "Waring Commons",
    category: "Entree / Pasta",
    rating: 8.7,
    sentiment: "Favorite",
    notes: "A-tier pasta dish; rich, flavorful seafood cream sauce with tender ravioli.",
  },
  {
    date: "2026-09-21",
    meal: "Dinner",
    dish: "Carved Beef Brisket",
    location: "Waring Commons",
    category: "Entree",
    rating: 6.8,
    sentiment: "Mixed",
    notes:
      "High batch variance: first serving sitting under lamps was dry and tough; freshly restocked second pan was much more tender, saving the meal.",
  },
  {
    date: "2026-09-21",
    meal: "Dinner",
    dish: "Thin Sliced Potatoes",
    location: "Waring Commons",
    category: "Side",
    rating: 6.8,
    sentiment: "Neutral",
    notes: "Decent texture but average overall seasoning; unremarkable side.",
  },
  {
    date: "2026-09-21",
    meal: "Dinner",
    dish: "Fresh Baked Chocolate Chip Cookie",
    location: "Waring Commons",
    category: "Dessert",
    rating: 8.0,
    sentiment: "Liked",
    notes: "Freshly baked, soft and warm sweet finish.",
  },
];
